import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Toaster richColors/>
      <body className={inter.className}>
        <main className="h-min-screen flex flex-col justify-center items-center">
          <NavBar />
          <div className="mt-16">
           {children}
          </div>
        </main>
      </body>
    </html>
  );
}
